### ISSUE TITLE
What should we display if a participant has more than one form(s) completed?

### ISSUE THREAD

**Issue by sbohner14335** [Capping-CPCA/Web-App#179]
This is a question I have for the edit/update form functionality that we are implementing.

What should we display on the edit/update page?

**Comment by michelleburd** [comment]
Where will you be implementing this feature? As a link from the "View Participant" page? If so, you could follow the way classes/curricula/locations is displayed. 
![demo](https://user-images.githubusercontent.com/9563621/33334880-70b631e2-d439-11e7-85e3-8398d1853a1f.png)
Instead of a search bar you could title the page something like "_Participant's Name_'s Completed Forms". Perhaps you could also include some information about the form in each card since it is possible to have multiple referral forms for one participant.
