### ISSUE TITLE
Reports Pages

### ISSUE THREAD

**Issue by stickzman** [Capping-CPCA/Web-App#31]
Add the Monthly, Quarterly, and Year-End Report pages to the UI

**Comment by ghost** [comment]
The layout mock is completed on the reports branch, we could merge that into develop

https://github.com/Capping-CPCA/Web-App/tree/31-reports-pages

**Comment by blackjack26** [comment]
@Capping-CPCA/team-6  If the pages are just mocked up with no real functionality, I would suggest, making a merge request for this branch (since you did add the pages to the UI), and then open up a new issue to address adding the functionality to the report pages (and make a new branch since this one would be deleted after the merge)
