### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by k6789j** [Capping-CPCA/Web-App#64]
Code no longer catches 500 errors.  Used to bring the user to error.php, like in this screenshot:

![image](https://user-images.githubusercontent.com/9339151/32203534-285c3e86-bdba-11e7-9457-f3a3edf43d88.png)

now it just shows a blank white screen, like in this screenshot:

![image](https://user-images.githubusercontent.com/9339151/32203512-03860e84-bdba-11e7-9cac-8c0ea3d576c1.png)

**Comment by blackjack26** [comment]
Nothing has been changed with error handling since that first screenshot and it seems to be working fine on <http://10.11.12.28>. Not sure what this error is.

**Comment by dtoverington** [comment]
The issue isn't that the 500 errors occur, actually, the above error in particular was created on purpose to test error handling. Both screenshots above are the result of the same mistake in the db_config.ini file. The only issue was that it appeared that the older code (top screenshot) was able to handle and display the error text rather than the newer version (lower screenshot) that did not return any helpful info on screen or in the console for debugging. We weren't sure if you knew of anything that was different or how this change in error handling could have happened.

**Comment by blackjack26** [comment]
Okay, so in `v0.1.5` I changed some errors to be thrown as exceptions instead of displaying an error to the page (since it is better practice to do a try-catch for exceptions). When I do remove that config file it shows me an error on the page but in plain text. Could just be a configuration setting on the server. But i'll label this as a bug since the ` parse_ini_file(../core/database/db_config.ini)` is not in a try-catch.

**Comment by blackjack26** [comment]
@dtoverington in the `config.php` file, there is a line that says:
```php
error_reporting(E_ALL);
// TODO: turn off error reporting in production
//error_reporting(0);
```

You should uncomment those lines an turn on `error_reporting(0)`.
That'll display the pretty message.
