### ISSUE TITLE
Blank Class

### ISSUE THREAD

**Issue by KCoterwas** [Capping-CPCA/Web-App#94]
On .33 there's a completely blank class under Classes that is unable to be interacted with.
![image](https://user-images.githubusercontent.com/9370555/32511301-5cada636-c3c1-11e7-8d55-c1e7054f4032.png)

**Comment by blackjack26** [comment]
This might've occurred if someone simply added a class with a single space as the name. In my archive pull request #89 I've made it so you can't just have a name with only spaces. Also this row would need to be removed from the database because technically it shouldn't be able to exist after that pull request.
